name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Analyze with SonarCloud
    runs-on: windows-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Sonar build-wrapper for C++
      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5

      # Build your project with build-wrapper
      - name: Build with MSBuild
        run: |
          mkdir build
          cd build
          build-wrapper-win-x86-64.exe --out-dir ../${{ env.BUILD_WRAPPER_OUT_DIR }} msbuild ../YourPro_
